server:
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: server
    trust-store: classpath:ssl/truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    client-auth: need
  port: 8443
